# Generated by Django 5.1.4 on 2025-01-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_factura',
            name='producto_precio',
            field=models.FloatField(default=0),
        ),
    ]
