# Generated by Django 5.1.4 on 2025-01-10 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_uso', models.IntegerField()),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('estadistica_list', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='estadistica_mesa',
            fields=[
                ('estadistica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Estadistica.estadistica')),
                ('mesa_mas_usada', models.CharField(max_length=50)),
            ],
            bases=('Estadistica.estadistica',),
        ),
        migrations.CreateModel(
            name='estadistica_mesero',
            fields=[
                ('estadistica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Estadistica.estadistica')),
                ('mejor_mesero', models.CharField(max_length=50)),
            ],
            bases=('Estadistica.estadistica',),
        ),
        migrations.CreateModel(
            name='estadistica_producto',
            fields=[
                ('estadistica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Estadistica.estadistica')),
                ('producto_mas_vendido', models.CharField(max_length=50)),
            ],
            bases=('Estadistica.estadistica',),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('impuesto', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
                ('item_factura_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='Estadistica.item_factura')),
            ],
        ),
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Estadistica.persona')),
                ('pedidosAtentidos', models.IntegerField()),
            ],
            bases=('Estadistica.persona',),
        ),
        migrations.AddField(
            model_name='item_factura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_factura', to='Estadistica.producto'),
        ),
    ]
