# Generated by Django 5.1.4 on 2025-01-13 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica_mesa',
            name='factura_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadistica_mesa', to='modulo6.factura'),
        ),
        migrations.AddField(
            model_name='estadistica_mesero',
            name='factura_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadistica_mesero', to='modulo6.factura'),
        ),
        migrations.AddField(
            model_name='estadistica_producto',
            name='item_factura_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadistica_producto', to='modulo6.item_factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='modulo6.mesa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='mesero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='modulo6.mesero'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='factura',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='modulo6.factura'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='grafico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='modulo6.grafico'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estadistica_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='modulo6.estadistica'),
        ),
    ]
