# Generated by Django 5.1.4 on 2025-01-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo6', '0002_estadistica_mesa_factura_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesero',
            old_name='pedidosAtentidos',
            new_name='pedidosAtendidos',
        ),
        migrations.RemoveField(
            model_name='estadistica_mesa',
            name='factura_list',
        ),
        migrations.RemoveField(
            model_name='estadistica_mesero',
            name='factura_list',
        ),
        migrations.RemoveField(
            model_name='estadistica_producto',
            name='item_factura_list',
        ),
        migrations.AddField(
            model_name='estadistica_mesa',
            name='factura_list',
            field=models.ManyToManyField(blank=True, related_name='estadistica_mesa', to='modulo6.factura'),
        ),
        migrations.AddField(
            model_name='estadistica_mesero',
            name='factura_list',
            field=models.ManyToManyField(blank=True, related_name='estadistica_mesero', to='modulo6.factura'),
        ),
        migrations.AddField(
            model_name='estadistica_producto',
            name='item_factura_list',
            field=models.ManyToManyField(blank=True, related_name='estadistica_producto', to='modulo6.item_factura'),
        ),
    ]
