# Generated by Django 5.1.4 on 2025-01-13 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_plato_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
