# Generated by Django 5.1.4 on 2025-01-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_plato_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='disponible',
            new_name='esta_disponible',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='item_pedido_list',
            field=models.ManyToManyField(blank=True, to='pedidos.itempedido'),
        ),
    ]
