# Generated by Django 5.1.4 on 2025-01-14 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_rename_disponible_mesa_esta_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='item_pedido_list',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido_list', to='pedidos.pedido'),
            preserve_default=False,
        ),
    ]
