# Generated by Django 5.1.4 on 2025-01-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_pedido_item_pedido_list_itempedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='item_pedido_list',
            field=models.ManyToManyField(blank=True, to='pedidos.itempedido'),
        ),
    ]
