# Generated by Django 5.1.4 on 2025-01-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='xd',
        ),
    ]
